# Generated by Django 5.2.6 on 2025-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musubiapp', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('shipping', 'Shipping'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
