# Generated by Django 5.2.6 on 2025-11-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musubiapp', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
