# Generated by Django 5.2.6 on 2025-11-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musubiapp', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musubiapp.reservation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_preparing', 'Order Preparing'), ('order_shipping', 'Order Shipping'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('new_reservation', 'New Reservation'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled')], max_length=30),
        ),
    ]
