# Generated by Django 5.2.6 on 2025-11-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musubiapp', '0011_add_reservation_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
