# Generated by Django 5.2.6 on 2025-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musubiapp', '0012_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Delivery address for pre-ordered items', null=True),
        ),
    ]
